services:
  - type: web
    runtime: docker
    name: koi-control-application
    repo: https://github.com/trungksdoa/SWP_Project_Topic_7.git
    plan: free
    branch: main
    rootDir: ./Koi_control_application
    dockerfilePath: ./Koi_control_application/Dockerfile
    dockerContext: ./Koi_control_application
    pullRequestPreviewsEnabled: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://koifishcontrol.mysql.database.azure.com:3306
      - key: SPRING_DATASOURCE_USERNAME
        value: adminuser
      - key: SPRING_DATASOURCE_PASSWORD
        value: g#H-GthWyfq_2bKs;7'R9}
      - key: SPRING_DATABASE_NAME
        value: koicontrol
    region: singapore
    healthCheckPath: /actuator/health
    dockerCommand: java -jar app.jar
