services:
  - type: web
    runtime: docker
    name: koi-control-application
    repo: https://github.com/trungksdoa/SWP_Project_Topic_7.git
    plan: free
    branch: main
    rootDir: Koi_control_application
    dockerfilePath: Dockerfile
    dockerContext: .
    pullRequestPreviewsEnabled: true
    buildCommand: ./gradlew build -x test
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://koifishcontrol.mysql.database.azure.com:3306/koicontrol
      - key: SPRING_DATASOURCE_USERNAME
        value: adminuser
      - key: SPRING_DATASOURCE_PASSWORD
        value: g#H-GthWyfq_2bKs;7'R9}
    region: singapore
    healthCheckPath: /actuator/health
