# spring:
#   datasource:
#     url: ${SPRING_DATASOURCE_URL}/${SPRING_DATABASE_NAME}
#     username: ${SPRING_DATASOURCE_USERNAME}
#     password: ${SPRING_DATASOURCE_PASSWORD}
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
#     database-platform: org.hibernate.dialect.MySQLDialect
# server:
#   port

app:
  jwt:
    secret: SecretKeyToGenJWTs

springdoc:
  api-docs:
    path: /api-docs
#    swagger-ui:
#      path: /swagger-ui.html
openapi:
  service:
    title: Koi Control Application
    description: Koi Control Application
    server:
      url: https://koi-controls-e5hxekcpd0cmgjg2.eastasia-01.azurewebsites.net
    version: 1.0.0
    contact:
      name: Koi Control Application
      email: trungksdoa@gmail.com
    api-docs: /v3/api-docs

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-email-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  web:
    resources:
      add-mappings: false

  application:
    name: Koi_control_application
  datasource:
    url: jdbc:mysql://koifishcontrol.mysql.database.azure.com:3306/koicontrol
    username: adminuser
    password: g#H-GthWyfq_2bKs;7'R9}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true

server:
  error:
    whitelabel:
      enabled: false
logging:
  level:
    org.springframework.web: DEBUG
    com.product.server.koi_control_application: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

