app:
  jwt:
    secret: SecretKeyToGenJWTs
  schedule:
     task:
       update-order-status:
         cron: 0 0 1 * * ? # 1h AM
#         cron: 0 0 1 * * ? # 1h AM



springdoc:
  api-docs:
    path: /api-docs

openapi:
  service:
    tilte: Koi Control Application
    description: Koi Control Application
    version: 1.0.0
    contact:
      name: Koi Control Application
      email: "trungksdoa@gmail.com"
    api-docs: /v3/api-docs
    servers:
      prod: https://koi-controls-e5hxekcpd0cmgjg2.eastasia-01.azurewebsites.net
      dev:  http://localhost:8080 

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

spring:
  jackson:
    time-zone= Asia/Ho_Chi_Minh
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  web:
    resources:
      add-mappings: false

  application:
    name: Koi_control_application
  datasource:
    url: jdbc:mysql://koifishcontrol.mysql.database.azure.com:3306/koicontrol
    username: adminuser
    password: g#H-GthWyfq_2bKs;7'R9}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true

server:
  error:
    whitelabel:
      enabled: false
logging:
  level:
    org.springframework.web: DEBUG
    com.product.server.koi_control_application: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

