# spring:
#   datasource:
#     url: ${SPRING_DATASOURCE_URL}/${SPRING_DATABASE_NAME}
#     username: ${SPRING_DATASOURCE_USERNAME}
#     password: ${SPRING_DATASOURCE_PASSWORD}
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
#     database-platform: org.hibernate.dialect.MySQLDialect
# server:
#   port
spring:
  application:
    name: Koi_control_application
  datasource:
    url: jdbc:mysql://koifishcontrol.mysql.database.azure.com:3306/koicontrol
    username: adminuser
    password: g#H-GthWyfq_2bKs;7'R9}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
