name: Build and deploy JAR app to Azure Web App - koi-control

on:
  push:
    branches:
      - main
    paths:
      - 'Koi_control_application/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Make Gradlew Executable
        run: chmod +x ./Koi_control_application/gradlew

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: ./Koi_control_application

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/Koi_control_application/build/libs/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3438CDF850EF45B3A93E2EF64D828E2C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A82A4C602B764249AE9B518952914E61 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1F2BB7BB61074DC2A4251608D924DC28 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'koi-control'
          slot-name: 'Production'
          package: '*.jar'
