name: Build and deploy JAR app to Azure Web App - koi-controls

on:
  push:
    branches:
      - main
    paths:
      - 'Koi_control_application/**'  # Run only if anychange in this folder
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Grant execute permission for gradlew
        run: chmod +x ./Koi_control_application/gradlew

      - name: Clean Gradle Cache
        run: ./gradlew clean --build-cache
        working-directory: ./Koi_control_application
        
      - name: Build with Gradle
        run: ./gradlew build -refresh-dependencies
        working-directory: ./Koi_control_application
        
        env:  
          SPRING_PROFILES_ACTIVE: prod
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/Koi_control_application/build/libs/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'koi-controls'
          slot-name: 'Production'
          package: '*-SNAPSHOT.jar'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2C87E69868144C538DB8781A4F2595C5 }}
